;******************************************************************************************************
; 帳票全般設定
;******************************************************************************************************
[SETTING]

;*** タイトル
title=ご来場者カード

;*** 用紙の向き(P=縦, L=横)
orientation=P

;デバッグ用（全項目に枠線が付き、赤フォントで、ページ上部にルーラーが出る）
;debug=1

;******************************************************************************************************
; テンプレート設定
;******************************************************************************************************
;★★★★★★★★★★★★★★★★★★★★★
; テンプレ1
;★★★★★★★★★★★★★★★★★★★★★
[TEMPLATE_1]
;*** テンプレートファイル名
tpl_name=tpl.pdf

;*** 綴りページ数（３枚綴りなら「3」を指定）
pages=1

;*** リスト系かどうか(リスト系：yes、単票系：no） ※単票の３枚綴りなどは「no」とし、pagesで綴り枚数を指定する
list=no

;*** リスト系の場合１ページ内の行数
rows=1

;*** リスト系の場合１行あたりの高さ
height=1



;******************************************************************************************************
; 項目設定
;******************************************************************************************************
;
; 詳しくは /lib/pdf_lib/pdf_lib.php のコメント参照
;
;


;*************** ユーザー情報
;[user_info]
;tpl=TEMPLATE_1
;type=textarea
;x = 48
;y = 19
;w = 90
;h = 30
;align = L
;font_name=hggothice
;font_size = 10

;*************** 企業名
[kigyou_name]
tpl=TEMPLATE_1
type=normal
x = 7
y = 58
w = 93
h = 10
align = L
font_name=hggothice
font_size = 20

;*************** ユーザー名
[user_name]
tpl=TEMPLATE_1
type=normal
x = 7
y = 70
w = 93
h = 10
align = L
font_name=hggothice
font_size = 20

;*************** AC所属（部署・支店）
[syozoku_name]
tpl=TEMPLATE_1
type=normal
x = 7
y = 88
w = 68
h = 10
align = L
font_name=hggothice
font_size = 9

;*************** QR
[qr_code]
tpl=TEMPLATE_1
type=qrcode
qrtype=M
x = 67
y = 98
w = 28
h = 28
;font_name=msgothic
;font_size = 12

;*************** QR文字
;[qr_code_str]
;tpl=TEMPLATE_1
;type=normal
;x = 71
;y = 87
;w = 43
;align = C
;font_name=msgothic
;font_size = 10


